{% set name = "html2text" %}
{% set version = "2025.4.15" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 948a645f8f0bc3abe7fd587019a2197a12436cd73d0d4908af95bfc8da337588

build:
  number: 0
  noarch: python
  entry_points:
    - html2text = html2text.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - html2text
  commands:
    - html2text --help
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Alir3z4/html2text/
  license: GNU General Public (GPL)
  license_family: LGPL
  license_file: COPYING
  summary: Turn HTML into equivalent Markdown-structured text.

extra:
  recipe-maintainers:
    - jan-janssen
    - nehaljwani
