{% set name = "html2text" %}
{% set version = "2024.2.26" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05f8e367d15aaabc96415376776cdd11afd5127a77fce6e36afc60c563ca2c32

build:
  number: 2
  noarch: python
  entry_points:
    - html2text = html2text.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - html2text
  commands:
    - html2text --help
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Alir3z4/html2text/
  license: GNU General Public (GPL)
  license_family: LGPL
  license_file: COPYING
  summary: Turn HTML into equivalent Markdown-structured text.

extra:
  recipe-maintainers:
    - jan-janssen
    - nehaljwani
